import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'Haris Maulana - PORTFOLIO',
  description: 'Generated by create next app & Laravel',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
